















import type { QuestionBankItem } from "../../types"; 

const jambBiologyHardQuestions: QuestionBankItem[] = [
  

{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A plant is placed in darkness for several days but continues to respire. Which observation would best demonstrate that respiration is occurring in the living plant?", styles: [] }],
    },
  ],
  question: "A plant is placed in darkness for several days but continues to respire. Which observation would best demonstrate that respiration is occurring in the living plant?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Evidence of life processes",
  section: "objective",
  options: [
    { label: "A", value: "Carbon dioxide is released while stored food is being utilized" },
    { label: "B", value: "The leaves remain green throughout the period" },
    { label: "C", value: "The plant remains fixed in one position" },
    { label: "D", value: "The plant produces chlorophyll in complete darkness" },
  ],
  correctAnswers: ["Carbon dioxide is released while stored food is being utilized"],
  explanation: "Respiration can continue without light by using stored organic food and releasing carbon dioxide.",
  explanationSteps: [
    "Darkness prevents photosynthesis but does not stop cellular respiration.",
    "Utilization of stored food with carbon dioxide production provides evidence of respiration.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "Two organisms obtain food from their surroundings, but only one manufactures its own organic food. Which combination of observations would most strongly distinguish the two organisms?", styles: [] }],
    },
  ],
  question: "Two organisms obtain food from their surroundings, but only one manufactures its own organic food. Which combination of observations would most strongly distinguish the two organisms?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Nutrition and life processes",
  section: "objective",
  options: [
    { label: "A", value: "The first depends on external organic nutrients while the second synthesizes organic food from inorganic materials" },
    { label: "B", value: "The first respires while the second does not" },
    { label: "C", value: "The first reproduces while the second remains permanently unchanged" },
    { label: "D", value: "The first excretes while the second cannot remove wastes" },
  ],
  correctAnswers: ["The first depends on external organic nutrients while the second synthesizes organic food from inorganic materials"],
  explanation: "The major distinction is the mode of nutrition, not whether other life processes occur.",
  explanationSteps: [
    "Both organisms may perform respiration, excretion and reproduction.",
    "An autotrophic organism manufactures organic food, whereas a heterotrophic organism obtains organic nutrients externally.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A researcher observes an organism that becomes less active when its body temperature falls and more active when the temperature rises. Which conclusion is most appropriate?", styles: [] }],
    },
  ],
  question: "A researcher observes an organism that becomes less active when its body temperature falls and more active when the temperature rises. Which conclusion is most appropriate?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Response to environmental changes",
  section: "objective",
  options: [
    { label: "A", value: "The organism's metabolic processes are influenced by temperature" },
    { label: "B", value: "The organism cannot perform respiration at any temperature" },
    { label: "C", value: "The organism does not respond to environmental stimuli" },
    { label: "D", value: "The organism must obtain all nutrients through photosynthesis" },
  ],
  correctAnswers: ["The organism's metabolic processes are influenced by temperature"],
  explanation: "Temperature affects enzyme-controlled metabolic reactions, so changes in temperature can alter activity.",
  explanationSteps: [
    "Many metabolic reactions depend on enzyme activity.",
    "Temperature changes can therefore alter the rate of physiological activity.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "An organism increases its movement immediately after being exposed to intense light. Which evidence would be strongest in classifying the movement as a response to a stimulus?", styles: [] }],
    },
  ],
  question: "An organism increases its movement immediately after being exposed to intense light. Which evidence would be strongest in classifying the movement as a response to a stimulus?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Sensitivity",
  section: "objective",
  options: [
    { label: "A", value: "The change in movement occurs after the environmental change is detected" },
    { label: "B", value: "The organism possesses stored food" },
    { label: "C", value: "The organism eventually produces offspring" },
    { label: "D", value: "The organism releases metabolic waste" },
  ],
  correctAnswers: ["The change in movement occurs after the environmental change is detected"],
  explanation: "Sensitivity involves detecting a stimulus and producing an appropriate response.",
  explanationSteps: [
    "Light is an environmental stimulus.",
    "A change in movement following exposure demonstrates a response to that stimulus.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A single-celled organism is transferred from a nutrient-rich medium into a medium containing little available food. Which sequence best represents the immediate physiological priorities of the organism?", styles: [] }],
    },
  ],
  question: "A single-celled organism is transferred from a nutrient-rich medium into a medium containing little available food. Which sequence best represents the immediate physiological priorities of the organism?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Integrated life processes",
  section: "objective",
  options: [
    { label: "A", value: "Maintain essential metabolism, conserve resources and adjust activity to the new conditions" },
    { label: "B", value: "Stop all respiration and immediately begin reproduction" },
    { label: "C", value: "Increase waste production without changing metabolism" },
    { label: "D", value: "Stop responding to environmental changes" },
  ],
  correctAnswers: ["Maintain essential metabolism, conserve resources and adjust activity to the new conditions"],
  explanation: "Living organisms must maintain essential functions while adjusting to changing environmental conditions.",
  explanationSteps: [
    "Reduced nutrients create a limitation on energy and material supply.",
    "The organism must regulate activity and conserve resources while maintaining essential metabolism.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A biologist compares two organisms. Organism X has specialized structures for obtaining nutrients, transporting substances and removing wastes, whereas organism Y performs these functions within one cell. What does this difference most strongly suggest?", styles: [] }],
    },
  ],
  question: "A biologist compares two organisms. Organism X has specialized structures for obtaining nutrients, transporting substances and removing wastes, whereas organism Y performs these functions within one cell. What does this difference most strongly suggest?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Levels of organization",
  section: "objective",
  options: [
    { label: "A", value: "Organism X has greater structural specialization than organism Y" },
    { label: "B", value: "Organism Y is not a living organism" },
    { label: "C", value: "Organism X cannot perform respiration" },
    { label: "D", value: "Organism Y must reproduce only sexually" },
  ],
  correctAnswers: ["Organism X has greater structural specialization than organism Y"],
  explanation: "Multicellular organisms often have specialized structures that divide physiological functions among tissues and organs.",
  explanationSteps: [
    "Organism Y performs several functions within a single cell.",
    "The presence of specialized structures in X indicates a higher level of structural organization.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A scientist prevents an organism from obtaining oxygen but supplies it with abundant glucose. After some time, the organism produces less energy but remains alive. Which process most likely explains this observation?", styles: [] }],
    },
  ],
  question: "A scientist prevents an organism from obtaining oxygen but supplies it with abundant glucose. After some time, the organism produces less energy but remains alive. Which process most likely explains this observation?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Respiration",
  section: "objective",
  options: [
    { label: "A", value: "Anaerobic respiration is supplying some energy from glucose" },
    { label: "B", value: "Photosynthesis is replacing respiration" },
    { label: "C", value: "Excretion is generating energy from glucose" },
    { label: "D", value: "Growth is occurring without any energy requirement" },
  ],
  correctAnswers: ["Anaerobic respiration is supplying some energy from glucose"],
  explanation: "Some organisms can obtain limited energy from glucose without oxygen through anaerobic respiration.",
  explanationSteps: [
    "Glucose can be broken down without oxygen in anaerobic conditions.",
    "This produces less energy than aerobic respiration but can temporarily sustain life.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A living organism is deprived of water but remains alive for several hours. Which change would provide the strongest evidence that the deprivation is beginning to affect its normal physiological functions?", styles: [] }],
    },
  ],
  question: "A living organism is deprived of water but remains alive for several hours. Which change would provide the strongest evidence that the deprivation is beginning to affect its normal physiological functions?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Regulation and survival",
  section: "objective",
  options: [
    { label: "A", value: "Reduced metabolic activity and impaired transport of dissolved substances" },
    { label: "B", value: "Permanent increase in reproduction" },
    { label: "C", value: "Complete independence from environmental conditions" },
    { label: "D", value: "Increased production of chlorophyll in all tissues" },
  ],
  correctAnswers: ["Reduced metabolic activity and impaired transport of dissolved substances"],
  explanation: "Water is essential for many biochemical reactions and for transport within organisms.",
  explanationSteps: [
    "Water forms an important medium for cellular reactions.",
    "Water loss can therefore disrupt metabolism and internal transport before death occurs.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "An organism grows from a microscopic size to a much larger size while maintaining the same basic body plan. Which explanation best accounts for this change?", styles: [] }],
    },
  ],
  question: "An organism grows from a microscopic size to a much larger size while maintaining the same basic body plan. Which explanation best accounts for this change?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Growth",
  section: "objective",
  options: [
    { label: "A", value: "Increase in cell number and/or cell size accompanied by synthesis of new cellular materials" },
    { label: "B", value: "Conversion of all cells into reproductive cells" },
    { label: "C", value: "Complete cessation of cellular metabolism" },
    { label: "D", value: "Permanent removal of all cellular water" },
  ],
  correctAnswers: ["Increase in cell number and/or cell size accompanied by synthesis of new cellular materials"],
  explanation: "Growth results from increases in cellular material, cell size, cell number, or combinations of these processes.",
  explanationSteps: [
    "Cells synthesize additional materials and may divide.",
    "The resulting increase in cellular mass produces growth while maintaining organismal organization.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A population contains organisms that differ in their ability to tolerate high temperatures. During a prolonged period of unusually high temperature, which outcome would most likely occur if the difference is inherited?", styles: [] }],
    },
  ],
  question: "A population contains organisms that differ in their ability to tolerate high temperatures. During a prolonged period of unusually high temperature, which outcome would most likely occur if the difference is inherited?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Variation and survival",
  section: "objective",
  options: [
    { label: "A", value: "Heat-tolerant individuals are more likely to survive and contribute offspring" },
    { label: "B", value: "All individuals immediately become heat tolerant" },
    { label: "C", value: "Only the largest individuals can reproduce regardless of tolerance" },
    { label: "D", value: "Environmental temperature cannot influence survival" },
  ],
  correctAnswers: ["Heat-tolerant individuals are more likely to survive and contribute offspring"],
  explanation: "Inherited variation can influence survival and reproductive success under changing environmental conditions.",
  explanationSteps: [
    "High temperature creates a selection pressure.",
    "Individuals with inherited tolerance have a greater chance of surviving and reproducing.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A researcher removes an organism's ability to detect changes in its surroundings while leaving respiration and nutrition intact. Which life process has been most directly disrupted?", styles: [] }],
    },
  ],
  question: "A researcher removes an organism's ability to detect changes in its surroundings while leaving respiration and nutrition intact. Which life process has been most directly disrupted?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Sensitivity and coordination",
  section: "objective",
  options: [
    { label: "A", value: "Sensitivity" },
    { label: "B", value: "Nutrition" },
    { label: "C", value: "Respiration" },
    { label: "D", value: "Excretion" },
  ],
  correctAnswers: ["Sensitivity"],
  explanation: "Sensitivity is the ability to detect and respond to changes in the internal or external environment.",
  explanationSteps: [
    "The organism can still obtain nutrients and release energy.",
    "Its inability to detect environmental changes specifically affects sensitivity.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A multicellular organism has many cells that perform different functions. Which observation would provide the strongest evidence that these cells depend on one another?", styles: [] }],
    },
  ],
  question: "A multicellular organism has many cells that perform different functions. Which observation would provide the strongest evidence that these cells depend on one another?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Cellular specialization",
  section: "objective",
  options: [
    { label: "A", value: "Failure of one specialized system causes disturbances in functions performed by other systems" },
    { label: "B", value: "Every cell performs exactly the same function" },
    { label: "C", value: "No cell exchanges materials with another cell" },
    { label: "D", value: "All cells remain permanently independent of the environment" },
  ],
  correctAnswers: ["Failure of one specialized system causes disturbances in functions performed by other systems"],
  explanation: "Specialized cells and organs are interdependent because the activities of one system often support others.",
  explanationSteps: [
    "Division of labour creates functional dependence among specialized structures.",
    "Disruption of one system can therefore affect other physiological processes.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "An organism increases its rate of respiration during intense activity. Which combination of changes would best explain why this response is advantageous?", styles: [] }],
    },
  ],
  question: "An organism increases its rate of respiration during intense activity. Which combination of changes would best explain why this response is advantageous?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Respiration and energy demand",
  section: "objective",
  options: [
    { label: "A", value: "Greater energy demand requires faster breakdown of respiratory substrates" },
    { label: "B", value: "Greater energy demand eliminates the need for nutrients" },
    { label: "C", value: "Respiration directly replaces all forms of movement" },
    { label: "D", value: "Increased respiration stops waste formation" },
  ],
  correctAnswers: ["Greater energy demand requires faster breakdown of respiratory substrates"],
  explanation: "Increased activity requires more ATP, so respiratory metabolism must increase to supply energy.",
  explanationSteps: [
    "Muscle and other active cells consume more energy during intense activity.",
    "An increased respiratory rate helps provide the additional ATP required.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A plant develops toward a light source even though it is not capable of moving from one location to another. Which conclusion best demonstrates why movement is still considered a characteristic of living organisms?", styles: [] }],
    },
  ],
  question: "A plant develops toward a light source even though it is not capable of moving from one location to another. Which conclusion best demonstrates why movement is still considered a characteristic of living organisms?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Movement in organisms",
  section: "objective",
  options: [
    { label: "A", value: "Living organisms can show movement of parts or growth in response to environmental conditions" },
    { label: "B", value: "Only organisms that move from place to place are living" },
    { label: "C", value: "Plants are incapable of responding to stimuli" },
    { label: "D", value: "Plant growth is unrelated to environmental conditions" },
  ],
  correctAnswers: ["Living organisms can show movement of parts or growth in response to environmental conditions"],
  explanation: "Movement in plants can occur through growth or movement of structures rather than locomotion.",
  explanationSteps: [
    "The plant responds to directional light.",
    "Growth of its tissues changes its position or orientation, demonstrating movement.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A living organism is placed in an environment where food, water and oxygen are available, but its internal temperature changes widely with the environment. Which inference is most reasonable?", styles: [] }],
    },
  ],
  question: "A living organism is placed in an environment where food, water and oxygen are available, but its internal temperature changes widely with the environment. Which inference is most reasonable?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Regulation of internal conditions",
  section: "objective",
  options: [
    { label: "A", value: "Its internal temperature is strongly influenced by external temperature" },
    { label: "B", value: "It cannot carry out respiration" },
    { label: "C", value: "It does not require energy" },
    { label: "D", value: "It cannot respond to stimuli" },
  ],
  correctAnswers: ["Its internal temperature is strongly influenced by external temperature"],
  explanation: "Some organisms rely heavily on environmental temperature to determine their body temperature.",
  explanationSteps: [
    "External temperature changes are reflected in internal temperature.",
    "This indicates limited internal regulation of body temperature.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A culture of microorganisms shows rapid population increase when nutrients are abundant but little increase after nutrients become scarce. Which combination of processes most directly explains the initial population increase?", styles: [] }],
    },
  ],
  question: "A culture of microorganisms shows rapid population increase when nutrients are abundant but little increase after nutrients become scarce. Which combination of processes most directly explains the initial population increase?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Nutrition, growth and reproduction",
  section: "objective",
  options: [
    { label: "A", value: "Efficient nutrition, energy production, growth and reproduction" },
    { label: "B", value: "Permanent reduction in metabolism and complete cessation of reproduction" },
    { label: "C", value: "Excretion without nutrient uptake" },
    { label: "D", value: "Sensitivity without cellular activity" },
  ],
  correctAnswers: ["Efficient nutrition, energy production, growth and reproduction"],
  explanation: "Abundant nutrients support metabolism, growth and reproduction, allowing population size to increase.",
  explanationSteps: [
    "Nutrients provide materials and substrates for metabolism.",
    "Adequate energy and materials permit growth and production of new individuals.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "An organism produces a waste substance that becomes toxic if it accumulates inside its cells. Which life process becomes especially important in preventing the waste from reaching harmful concentrations?", styles: [] }],
    },
  ],
  question: "An organism produces a waste substance that becomes toxic if it accumulates inside its cells. Which life process becomes especially important in preventing the waste from reaching harmful concentrations?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Excretion and internal balance",
  section: "objective",
  options: [
    { label: "A", value: "Excretion" },
    { label: "B", value: "Reproduction" },
    { label: "C", value: "Growth" },
    { label: "D", value: "Nutrition" },
  ],
  correctAnswers: ["Excretion"],
  explanation: "Excretion removes metabolic waste products that could become harmful when accumulated.",
  explanationSteps: [
    "Metabolic reactions produce waste substances.",
    "Removing these substances prevents toxic accumulation and supports normal cellular function.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A species reproduces rapidly but has very little genetic variation. A sudden environmental change eliminates most of its members. Which explanation best accounts for its vulnerability?", styles: [] }],
    },
  ],
  question: "A species reproduces rapidly but has very little genetic variation. A sudden environmental change eliminates most of its members. Which explanation best accounts for its vulnerability?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Reproduction and variation",
  section: "objective",
  options: [
    { label: "A", value: "Few individuals are likely to possess inherited traits suited to the new conditions" },
    { label: "B", value: "Rapid reproduction always prevents adaptation" },
    { label: "C", value: "Reproduction removes all useful traits from populations" },
    { label: "D", value: "Environmental changes affect only non-living things" },
  ],
  correctAnswers: ["Few individuals are likely to possess inherited traits suited to the new conditions"],
  explanation: "Genetic variation increases the likelihood that some individuals possess traits suited to changing conditions.",
  explanationSteps: [
    "The population has limited inherited variation.",
    "A severe environmental change therefore leaves fewer individuals with potentially advantageous traits.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A living cell is supplied with nutrients but its oxygen supply is suddenly reduced. Which observation would indicate that the cell is compensating for the reduced oxygen availability?", styles: [] }],
    },
  ],
  question: "A living cell is supplied with nutrients but its oxygen supply is suddenly reduced. Which observation would indicate that the cell is compensating for the reduced oxygen availability?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Cellular respiration",
  section: "objective",
  options: [
    { label: "A", value: "Increased reliance on anaerobic energy production" },
    { label: "B", value: "Complete cessation of all metabolic activity" },
    { label: "C", value: "Immediate conversion of all nutrients into body structures" },
    { label: "D", value: "Permanent elimination of waste products" },
  ],
  correctAnswers: ["Increased reliance on anaerobic energy production"],
  explanation: "Cells may increase anaerobic pathways when oxygen becomes insufficient for normal aerobic respiration.",
  explanationSteps: [
    "Reduced oxygen limits aerobic energy production.",
    "Anaerobic pathways can provide a temporary alternative source of energy.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "An organism's cells continue carrying out chemical reactions, but the organism can no longer maintain stable internal conditions. Which conclusion is most appropriate?", styles: [] }],
    },
  ],
  question: "An organism's cells continue carrying out chemical reactions, but the organism can no longer maintain stable internal conditions. Which conclusion is most appropriate?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Homeostasis",
  section: "objective",
  options: [
    { label: "A", value: "Its metabolic activity may continue even though regulation of internal conditions has been impaired" },
    { label: "B", value: "The organism is necessarily dead because metabolism occurs" },
    { label: "C", value: "Homeostasis is unrelated to survival" },
    { label: "D", value: "Chemical reactions cannot occur in living organisms" },
  ],
  correctAnswers: ["Its metabolic activity may continue even though regulation of internal conditions has been impaired"],
  explanation: "Metabolism and homeostatic regulation are related but distinct aspects of living activity.",
  explanationSteps: [
    "Cells may continue biochemical reactions despite regulatory failure.",
    "Failure to maintain internal conditions can eventually compromise survival.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "Two organisms consume the same food source. Organism A converts a larger proportion of the absorbed nutrients into new tissue, while organism B releases more energy as heat. Which inference is most appropriate?", styles: [] }],
    },
  ],
  question: "Two organisms consume the same food source. Organism A converts a larger proportion of the absorbed nutrients into new tissue, while organism B releases more energy as heat. Which inference is most appropriate?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Nutrition, growth and metabolism",
  section: "objective",
  options: [
    { label: "A", value: "Organism A is allocating a greater proportion of absorbed nutrients toward growth or tissue formation" },
    { label: "B", value: "Organism B does not carry out respiration" },
    { label: "C", value: "Organism A cannot produce energy" },
    { label: "D", value: "Heat release proves that organism B is non-living" },
  ],
  correctAnswers: ["Organism A is allocating a greater proportion of absorbed nutrients toward growth or tissue formation"],
  explanation: "Absorbed nutrients can be used for energy production, growth, repair and other functions.",
  explanationSteps: [
    "Organism A retains more absorbed material in newly formed tissue.",
    "This suggests a greater allocation toward synthesis and growth.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A plant is exposed to drought and subsequently closes many of its stomata. Which combination best explains why this response can help the plant survive?", styles: [] }],
    },
  ],
  question: "A plant is exposed to drought and subsequently closes many of its stomata. Which combination best explains why this response can help the plant survive?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Response and survival",
  section: "objective",
  options: [
    { label: "A", value: "Reduced stomatal opening limits water loss, although it may also reduce carbon dioxide entry" },
    { label: "B", value: "Stomatal closure increases water loss and eliminates photosynthesis completely" },
    { label: "C", value: "Stomatal closure prevents all metabolic reactions" },
    { label: "D", value: "Stomata are reproductive structures that regulate seed formation" },
  ],
  correctAnswers: ["Reduced stomatal opening limits water loss, although it may also reduce carbon dioxide entry"],
  explanation: "Stomatal closure reduces transpiration but can also limit carbon dioxide uptake.",
  explanationSteps: [
    "Drought increases the risk of excessive water loss.",
    "Closing stomata conserves water but creates a trade-off by reducing gas exchange.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "An animal living in a cold environment has a metabolic rate that increases during periods of extreme cold. What is the most likely advantage of this response?", styles: [] }],
    },
  ],
  question: "An animal living in a cold environment has a metabolic rate that increases during periods of extreme cold. What is the most likely advantage of this response?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Metabolism and regulation",
  section: "objective",
  options: [
    { label: "A", value: "Increased metabolic activity can generate additional heat and support internal temperature regulation" },
    { label: "B", value: "Increased metabolism stops all energy expenditure" },
    { label: "C", value: "Increased metabolism prevents nutrient absorption" },
    { label: "D", value: "Increased metabolism eliminates the need for respiration" },
  ],
  correctAnswers: ["Increased metabolic activity can generate additional heat and support internal temperature regulation"],
  explanation: "Metabolic reactions release energy, some of which appears as heat.",
  explanationSteps: [
    "Cold conditions increase the need to maintain body temperature.",
    "Increasing metabolic activity can increase heat production.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A population of organisms is moved to an environment with a different food source. Individuals with structures better suited for obtaining the new food survive at higher rates. What does this observation demonstrate most directly?", styles: [] }],
    },
  ],
  question: "A population of organisms is moved to an environment with a different food source. Individuals with structures better suited for obtaining the new food survive at higher rates. What does this observation demonstrate most directly?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Adaptation and survival",
  section: "objective",
  options: [
    { label: "A", value: "Structural characteristics can influence survival when environmental conditions change" },
    { label: "B", value: "All organisms develop identical structures when exposed to the same environment" },
    { label: "C", value: "Nutrition has no relationship with survival" },
    { label: "D", value: "Environmental conditions cannot affect populations" },
  ],
  correctAnswers: ["Structural characteristics can influence survival when environmental conditions change"],
  explanation: "Structures that improve the ability to obtain resources can increase survival under particular environmental conditions.",
  explanationSteps: [
    "The new food source creates a different selection pressure.",
    "Individuals with suitable structures obtain food more effectively and have greater survival chances.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "An organism continues to take in nutrients but its cells cannot convert those nutrients into usable energy. Which combination of life processes would be most immediately affected?", styles: [] }],
    },
  ],
  question: "An organism continues to take in nutrients but its cells cannot convert those nutrients into usable energy. Which combination of life processes would be most immediately affected?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Interdependence of life processes",
  section: "objective",
  options: [
    { label: "A", value: "Movement, growth, active transport and other energy-dependent activities" },
    { label: "B", value: "Only reproduction, while every other activity remains unchanged" },
    { label: "C", value: "Only colour production, with no effect on metabolism" },
    { label: "D", value: "None, because nutrients themselves provide unlimited usable energy without metabolism" },
  ],
  correctAnswers: ["Movement, growth, active transport and other energy-dependent activities"],
  explanation: "Nutrients must be metabolized to provide usable cellular energy.",
  explanationSteps: [
    "ATP generated from metabolism powers many cellular activities.",
    "Failure to produce usable energy therefore disrupts numerous life processes simultaneously.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A researcher finds that an organism's cells become damaged when a particular waste product accumulates. Which sequence best represents the relationship involved?", styles: [] }],
    },
  ],
  question: "A researcher finds that an organism's cells become damaged when a particular waste product accumulates. Which sequence best represents the relationship involved?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Excretion and survival",
  section: "objective",
  options: [
    { label: "A", value: "Metabolism produces waste → waste accumulates → cellular function is impaired" },
    { label: "B", value: "Reproduction produces waste → waste becomes food → cells grow normally" },
    { label: "C", value: "Nutrition removes waste → waste increases energy production" },
    { label: "D", value: "Sensitivity produces waste → waste prevents all respiration" },
  ],
  correctAnswers: ["Metabolism produces waste → waste accumulates → cellular function is impaired"],
  explanation: "Metabolic wastes can become toxic when they are not adequately removed.",
  explanationSteps: [
    "Metabolic reactions generate waste products.",
    "If excretion is insufficient, accumulation can interfere with cellular processes.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A multicellular organism loses the ability of one tissue to supply nutrients to nearby cells. Which effect would most likely appear first?", styles: [] }],
    },
  ],
  question: "A multicellular organism loses the ability of one tissue to supply nutrients to nearby cells. Which effect would most likely appear first?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Division of labour and interdependence",
  section: "objective",
  options: [
    { label: "A", value: "Cells dependent on that supply experience reduced metabolic activity" },
    { label: "B", value: "All cells immediately become independent organisms" },
    { label: "C", value: "Reproduction immediately increases in every tissue" },
    { label: "D", value: "The affected tissue stops being part of the organism but remains fully functional" },
  ],
  correctAnswers: ["Cells dependent on that supply experience reduced metabolic activity"],
  explanation: "Cells require nutrients to support metabolism and cellular maintenance.",
  explanationSteps: [
    "Loss of nutrient supply limits substrates available to dependent cells.",
    "Reduced substrate availability can impair energy production and other metabolic activities.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "An organism responds to a harmful stimulus by moving away from it. Later, the organism stops responding even though the stimulus remains. Which explanation would best account for this observation?", styles: [] }],
    },
  ],
  question: "An organism responds to a harmful stimulus by moving away from it. Later, the organism stops responding even though the stimulus remains. Which explanation would best account for this observation?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Sensitivity and adaptation",
  section: "objective",
  options: [
    { label: "A", value: "The organism may have reduced responsiveness after repeated exposure to the stimulus" },
    { label: "B", value: "The organism necessarily stopped all metabolic activity" },
    { label: "C", value: "The stimulus became a nutrient" },
    { label: "D", value: "The organism permanently lost the ability to respire" },
  ],
  correctAnswers: ["The organism may have reduced responsiveness after repeated exposure to the stimulus"],
  explanation: "Repeated exposure can alter the responsiveness of some organisms or physiological systems.",
  explanationSteps: [
    "The initial response demonstrates sensitivity.",
    "A later reduction in response does not necessarily mean that all life processes have stopped.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A plant and an animal are both placed in darkness. The animal continues to obtain energy from food, while the plant eventually depends on stored food. Which conclusion is most scientifically justified?", styles: [] }],
    },
  ],
  question: "A plant and an animal are both placed in darkness. The animal continues to obtain energy from food, while the plant eventually depends on stored food. Which conclusion is most scientifically justified?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Nutrition and energy supply",
  section: "objective",
  options: [
    { label: "A", value: "Both organisms can respire using organic substrates, but the plant cannot continue photosynthesis without adequate light" },
    { label: "B", value: "The animal stops respiration in darkness" },
    { label: "C", value: "The plant can generate unlimited food without light" },
    { label: "D", value: "Neither organism requires stored organic matter" },
  ],
  correctAnswers: ["Both organisms can respire using organic substrates, but the plant cannot continue photosynthesis without adequate light"],
  explanation: "Darkness stops photosynthetic production of food but does not stop respiration.",
  explanationSteps: [
    "Plants and animals can release energy from organic substrates through respiration.",
    "Without light, a green plant must increasingly depend on previously stored food.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A scientist observes that an organism maintains nearly constant internal conditions despite large external fluctuations. Which additional observation would most strongly support the conclusion that the organism possesses effective regulatory mechanisms?", styles: [] }],
    },
  ],
  question: "A scientist observes that an organism maintains nearly constant internal conditions despite large external fluctuations. Which additional observation would most strongly support the conclusion that the organism possesses effective regulatory mechanisms?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Homeostasis",
  section: "objective",
  options: [
    { label: "A", value: "A deviation from the normal internal condition triggers a corrective response" },
    { label: "B", value: "The organism never interacts with its environment" },
    { label: "C", value: "The organism permanently stops metabolism when conditions change" },
    { label: "D", value: "The organism has no mechanisms for detecting changes" },
  ],
  correctAnswers: ["A deviation from the normal internal condition triggers a corrective response"],
  explanation: "Homeostasis depends on mechanisms that detect changes and initiate responses that restore suitable internal conditions.",
  explanationSteps: [
    "A regulatory system must detect deviations from an internal set range.",
    "A corrective response demonstrates active regulation rather than passive stability.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "An organism's population doubles rapidly when environmental resources are plentiful but declines after resources become scarce. Which relationship between life processes best explains the pattern?", styles: [] }],
    },
  ],
  question: "An organism's population doubles rapidly when environmental resources are plentiful but declines after resources become scarce. Which relationship between life processes best explains the pattern?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Population growth and resources",
  section: "objective",
  options: [
    { label: "A", value: "Resource availability influences nutrition, growth, reproduction and survival" },
    { label: "B", value: "Reproduction occurs independently of nutrition and energy supply" },
    { label: "C", value: "Resource shortage increases survival of every individual equally" },
    { label: "D", value: "Population size is completely unrelated to environmental conditions" },
  ],
  correctAnswers: ["Resource availability influences nutrition, growth, reproduction and survival"],
  explanation: "Environmental resources affect the ability of organisms to obtain energy and materials required for survival and reproduction.",
  explanationSteps: [
    "Abundant resources support metabolism, growth and reproductive activity.",
    "Resource scarcity increases competition and can reduce survival and reproduction.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A living organism receives adequate nutrients and oxygen but dies after its waste-removal system fails. What does this observation demonstrate?", styles: [] }],
    },
  ],
  question: "A living organism receives adequate nutrients and oxygen but dies after its waste-removal system fails. What does this observation demonstrate?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Interdependence of life processes",
  section: "objective",
  options: [
    { label: "A", value: "Life processes are interdependent and adequate nutrition alone cannot maintain life" },
    { label: "B", value: "Excretion is unnecessary when nutrients are available" },
    { label: "C", value: "Respiration cannot produce waste products" },
    { label: "D", value: "Waste products always improve cellular function" },
  ],
  correctAnswers: ["Life processes are interdependent and adequate nutrition alone cannot maintain life"],
  explanation: "Organisms depend on several coordinated processes to maintain viable internal conditions.",
  explanationSteps: [
    "Metabolism produces waste that must be removed.",
    "Failure of excretion can disrupt internal conditions despite adequate nutrient and oxygen supply.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A researcher compares a living seed with a dead seed under identical conditions. Both contain stored food, but only one eventually produces a seedling. Which observation would best establish that the living seed is metabolically active before visible growth occurs?", styles: [] }],
    },
  ],
  question: "A researcher compares a living seed with a dead seed under identical conditions. Both contain stored food, but only one eventually produces a seedling. Which observation would best establish that the living seed is metabolically active before visible growth occurs?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Metabolism and growth",
  section: "objective",
  options: [
    { label: "A", value: "The living seed consumes oxygen and releases carbon dioxide" },
    { label: "B", value: "The dead seed contains stored food" },
    { label: "C", value: "Both seeds have a similar external appearance" },
    { label: "D", value: "The living seed has a protective seed coat" },
  ],
  correctAnswers: ["The living seed consumes oxygen and releases carbon dioxide"],
  explanation: "Respiration provides evidence of active metabolism even before visible growth begins.",
  explanationSteps: [
    "A viable seed can respire while preparing for germination.",
    "Oxygen consumption and carbon dioxide release demonstrate metabolic activity.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A population contains organisms with different rates of reproduction. When food becomes scarce, individuals with lower energy requirements survive longer. If the trait is inherited, what is the likely long-term consequence?", styles: [] }],
    },
  ],
  question: "A population contains organisms with different rates of reproduction. When food becomes scarce, individuals with lower energy requirements survive longer. If the trait is inherited, what is the likely long-term consequence?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Variation and natural selection",
  section: "objective",
  options: [
    { label: "A", value: "The proportion of individuals with lower energy requirements may increase over generations" },
    { label: "B", value: "All individuals immediately acquire the trait during their lifetime" },
    { label: "C", value: "The trait disappears because food is scarce" },
    { label: "D", value: "Environmental scarcity prevents reproduction completely in every generation" },
  ],
  correctAnswers: ["The proportion of individuals with lower energy requirements may increase over generations"],
  explanation: "Inherited traits that improve survival can become more common through differential survival and reproduction.",
  explanationSteps: [
    "Food scarcity creates a selection pressure.",
    "Individuals with advantageous inherited traits are more likely to survive and reproduce.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A normally active organism becomes inactive after exposure to a substance that blocks enzyme activity. Which conclusion best connects this observation to the characteristics of living organisms?", styles: [] }],
    },
  ],
  question: "A normally active organism becomes inactive after exposure to a substance that blocks enzyme activity. Which conclusion best connects this observation to the characteristics of living organisms?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Metabolism and enzymes",
  section: "objective",
  options: [
    { label: "A", value: "Many life processes depend on enzyme-controlled biochemical reactions" },
    { label: "B", value: "Living organisms do not require chemical reactions" },
    { label: "C", value: "Enzymes are used only for reproduction" },
    { label: "D", value: "Movement occurs independently of metabolism in all organisms" },
  ],
  correctAnswers: ["Many life processes depend on enzyme-controlled biochemical reactions"],
  explanation: "Enzymes catalyze many metabolic reactions required for normal physiological activity.",
  explanationSteps: [
    "Blocking enzyme activity interferes with biochemical pathways.",
    "Reduced metabolic activity can consequently impair several life processes.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "An organism exposed to a new environmental condition initially shows reduced activity but later resumes normal activity. Which interpretation best explains this pattern?", styles: [] }],
    },
  ],
  question: "An organism exposed to a new environmental condition initially shows reduced activity but later resumes normal activity. Which interpretation best explains this pattern?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Adjustment to environmental changes",
  section: "objective",
  options: [
    { label: "A", value: "The organism may have adjusted physiologically to the new environmental condition" },
    { label: "B", value: "The organism permanently stopped responding to stimuli" },
    { label: "C", value: "The organism became non-living during the adjustment period" },
    { label: "D", value: "The environmental condition necessarily prevented all metabolism" },
  ],
  correctAnswers: ["The organism may have adjusted physiologically to the new environmental condition"],
  explanation: "Organisms can make physiological adjustments that improve functioning under changed conditions.",
  explanationSteps: [
    "The initial reduction indicates that the new condition affected physiological activity.",
    "Recovery suggests that the organism adjusted its functioning to the changed environment.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A scientist observes that removing one organ from an animal affects digestion, movement and growth even though those functions occur in different parts of the body. What does this observation demonstrate?", styles: [] }],
    },
  ],
  question: "A scientist observes that removing one organ from an animal affects digestion, movement and growth even though those functions occur in different parts of the body. What does this observation demonstrate?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Organ system interdependence",
  section: "objective",
  options: [
    { label: "A", value: "Organ systems are functionally interdependent" },
    { label: "B", value: "Each organ performs every life process independently" },
    { label: "C", value: "Growth does not require nutrients" },
    { label: "D", value: "Movement is unrelated to energy supply" },
  ],
  correctAnswers: ["Organ systems are functionally interdependent"],
  explanation: "Organ systems work together, so failure of one system can affect several physiological functions.",
  explanationSteps: [
    "Digestion supplies materials required by other tissues.",
    "Disruption of one system can therefore indirectly affect movement, growth and other processes.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "An organism receives sufficient food but continues to lose body mass because its rate of energy expenditure exceeds the energy supplied. Which conclusion is most appropriate?", styles: [] }],
    },
  ],
  question: "An organism receives sufficient food but continues to lose body mass because its rate of energy expenditure exceeds the energy supplied. Which conclusion is most appropriate?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Energy balance",
  section: "objective",
  options: [
    { label: "A", value: "The organism is using stored body materials to meet its energy requirements" },
    { label: "B", value: "Food intake always causes immediate growth" },
    { label: "C", value: "Respiration stops whenever body mass decreases" },
    { label: "D", value: "Excretion creates new body tissue" },
  ],
  correctAnswers: ["The organism is using stored body materials to meet its energy requirements"],
  explanation: "When energy expenditure exceeds energy intake, stored substances may be mobilized and body mass can decline.",
  explanationSteps: [
    "Cells continue requiring energy for metabolism and physiological activities.",
    "If dietary energy is insufficient, stored reserves can be broken down.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A researcher records the following observations about an unknown organism: it obtains nutrients, releases metabolic wastes, responds to light, grows and produces offspring. Which conclusion is best supported?", styles: [] }],
    },
  ],
  question: "A researcher records the following observations about an unknown organism: it obtains nutrients, releases metabolic wastes, responds to light, grows and produces offspring. Which conclusion is best supported?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Characteristics of living organisms",
  section: "objective",
  options: [
    { label: "A", value: "The organism exhibits several coordinated characteristics of life" },
    { label: "B", value: "Only reproduction demonstrates that the organism is alive" },
    { label: "C", value: "Growth alone proves that all organisms reproduce" },
    { label: "D", value: "Response to light proves that the organism does not respire" },
  ],
  correctAnswers: ["The organism exhibits several coordinated characteristics of life"],
  explanation: "Nutrition, excretion, sensitivity, growth and reproduction are characteristics associated with living organisms.",
  explanationSteps: [
    "The observations represent several independent life processes.",
    "Their coordinated occurrence provides strong evidence that the organism is living.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "Two populations of the same species occupy environments with different temperatures. Population A has a higher metabolic rate at low temperature, while population B performs better at high temperature. Which conclusion is most justified?", styles: [] }],
    },
  ],
  question: "Two populations of the same species occupy environments with different temperatures. Population A has a higher metabolic rate at low temperature, while population B performs better at high temperature. Which conclusion is most justified?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Physiological adaptation",
  section: "objective",
  options: [
    { label: "A", value: "The populations may possess physiological differences associated with their environments" },
    { label: "B", value: "Temperature cannot affect metabolic processes" },
    { label: "C", value: "Both populations must have identical physiological responses" },
    { label: "D", value: "Metabolic rate is independent of environmental conditions" },
  ],
  correctAnswers: ["The populations may possess physiological differences associated with their environments"],
  explanation: "Differences in physiological performance under different conditions can reflect adaptation or population-level variation.",
  explanationSteps: [
    "The two populations perform differently at different temperatures.",
    "This suggests that physiological characteristics may be associated with their respective environments.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A living cell is placed in a medium containing all essential nutrients but lacks a mechanism for regulating the movement of substances across its boundary. Which consequence is most likely?", styles: [] }],
    },
  ],
  question: "A living cell is placed in a medium containing all essential nutrients but lacks a mechanism for regulating the movement of substances across its boundary. Which consequence is most likely?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Regulation and cellular survival",
  section: "objective",
  options: [
    { label: "A", value: "The internal chemical conditions may become unsuitable for normal metabolism" },
    { label: "B", value: "The cell becomes independent of nutrients" },
    { label: "C", value: "The cell automatically increases reproduction" },
    { label: "D", value: "The cell no longer requires waste removal" },
  ],
  correctAnswers: ["The internal chemical conditions may become unsuitable for normal metabolism"],
  explanation: "Regulation of substances entering and leaving cells is essential for maintaining suitable internal conditions.",
  explanationSteps: [
    "Uncontrolled movement of substances can disturb internal concentrations.",
    "Changes in internal conditions can interfere with enzyme activity and metabolism.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A plant receives adequate water and minerals but is kept in complete darkness for a prolonged period. Which process would eventually be most directly limited?", styles: [] }],
    },
  ],
  question: "A plant receives adequate water and minerals but is kept in complete darkness for a prolonged period. Which process would eventually be most directly limited?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Interdependence of life processes",
  section: "objective",
  options: [
    { label: "A", value: "Production of new organic food by photosynthesis" },
    { label: "B", value: "Respiration using stored food" },
    { label: "C", value: "Excretion of metabolic wastes" },
    { label: "D", value: "Cellular response to environmental stimuli" },
  ],
  correctAnswers: ["Production of new organic food by photosynthesis"],
  explanation: "Photosynthesis requires light, so prolonged darkness prevents continued production of new organic food.",
  explanationSteps: [
    "Light energy is required for photosynthesis.",
    "The plant may continue respiration temporarily using stored food, but new food production is limited.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A population is exposed to a pollutant that interferes with reproduction but does not immediately kill adult organisms. Which population-level consequence is most likely if exposure continues?", styles: [] }],
    },
  ],
  question: "A population is exposed to a pollutant that interferes with reproduction but does not immediately kill adult organisms. Which population-level consequence is most likely if exposure continues?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Reproduction and population survival",
  section: "objective",
  options: [
    { label: "A", value: "Population size may decline as fewer offspring replace individuals that die" },
    { label: "B", value: "Population size must increase because adults remain alive" },
    { label: "C", value: "Reproduction is unrelated to population continuity" },
    { label: "D", value: "The pollutant necessarily increases genetic variation immediately" },
  ],
  correctAnswers: ["Population size may decline as fewer offspring replace individuals that die"],
  explanation: "Reproduction maintains populations by producing new individuals to replace those lost through death.",
  explanationSteps: [
    "Reduced reproductive success lowers the number of new individuals entering the population.",
    "Continued mortality can then cause population size to decline.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "An animal exposed to high environmental temperature increases blood flow near its body surface and begins rapid breathing. Which interpretation best connects these responses?", styles: [] }],
    },
  ],
  question: "An animal exposed to high environmental temperature increases blood flow near its body surface and begins rapid breathing. Which interpretation best connects these responses?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Coordination and regulation",
  section: "objective",
  options: [
    { label: "A", value: "The responses help increase heat loss and maintain a suitable internal temperature" },
    { label: "B", value: "The responses prevent all water loss from the body" },
    { label: "C", value: "The responses stop cellular respiration" },
    { label: "D", value: "The responses increase internal temperature deliberately" },
  ],
  correctAnswers: ["The responses help increase heat loss and maintain a suitable internal temperature"],
  explanation: "Increased peripheral blood flow and rapid breathing can contribute to heat dissipation.",
  explanationSteps: [
    "More blood near the body surface facilitates heat transfer.",
    "Rapid breathing can increase evaporative heat loss in suitable animals.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A microorganism is supplied with a radioactive nutrient molecule. The label later appears in newly formed cellular material. What does this observation demonstrate?", styles: [] }],
    },
  ],
  question: "A microorganism is supplied with a radioactive nutrient molecule. The label later appears in newly formed cellular material. What does this observation demonstrate?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Nutrition and growth",
  section: "objective",
  options: [
    { label: "A", value: "Materials obtained from the environment can be incorporated into the organism during growth" },
    { label: "B", value: "Nutrients are never chemically changed inside organisms" },
    { label: "C", value: "Growth occurs without nutrient uptake" },
    { label: "D", value: "Cellular material cannot originate from environmental nutrients" },
  ],
  correctAnswers: ["Materials obtained from the environment can be incorporated into the organism during growth"],
  explanation: "Nutrients provide raw materials that organisms transform and incorporate into cellular structures.",
  explanationSteps: [
    "The labelled nutrient enters the organism.",
    "Its later presence in cellular material shows that environmental materials can contribute to growth.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A population has abundant food but its numbers remain stable because individuals die at approximately the same rate at which new individuals are produced. Which conclusion is most appropriate?", styles: [] }],
    },
  ],
  question: "A population has abundant food but its numbers remain stable because individuals die at approximately the same rate at which new individuals are produced. Which conclusion is most appropriate?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Population balance",
  section: "objective",
  options: [
    { label: "A", value: "Population size can remain stable when recruitment approximately balances mortality" },
    { label: "B", value: "Abundant food guarantees unlimited population growth" },
    { label: "C", value: "Reproduction has no influence on population size" },
    { label: "D", value: "Death is unrelated to population dynamics" },
  ],
  correctAnswers: ["Population size can remain stable when recruitment approximately balances mortality"],
  explanation: "Population size depends on the balance among births, deaths and other demographic processes.",
  explanationSteps: [
    "New individuals increase population size.",
    "If losses approximately equal additions, the population remains relatively stable.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "An organism is unable to synthesize proteins even though amino acids are available in its cells. Which consequence would most directly threaten continued growth and repair?", styles: [] }],
    },
  ],
  question: "An organism is unable to synthesize proteins even though amino acids are available in its cells. Which consequence would most directly threaten continued growth and repair?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Growth and cellular maintenance",
  section: "objective",
  options: [
    { label: "A", value: "Failure to produce structural and functional proteins required for cellular maintenance" },
    { label: "B", value: "Immediate increase in oxygen production" },
    { label: "C", value: "Permanent increase in waste removal" },
    { label: "D", value: "Complete independence from cellular metabolism" },
  ],
  correctAnswers: ["Failure to produce structural and functional proteins required for cellular maintenance"],
  explanation: "Proteins are essential components of cells and include many enzymes and structural molecules.",
  explanationSteps: [
    "Growth and repair require synthesis of new cellular materials.",
    "Failure of protein synthesis therefore severely limits these processes.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A living organism is placed in an environment with adequate nutrients but an unsuitable pH. Its metabolic rate falls sharply. Which explanation is most likely?", styles: [] }],
    },
  ],
  question: "A living organism is placed in an environment with adequate nutrients but an unsuitable pH. Its metabolic rate falls sharply. Which explanation is most likely?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Environmental effects on metabolism",
  section: "objective",
  options: [
    { label: "A", value: "The altered pH may interfere with enzyme activity and metabolic reactions" },
    { label: "B", value: "Nutrients become unnecessary at unsuitable pH" },
    { label: "C", value: "pH affects only reproduction and never metabolism" },
    { label: "D", value: "Metabolic reactions are independent of chemical conditions" },
  ],
  correctAnswers: ["The altered pH may interfere with enzyme activity and metabolic reactions"],
  explanation: "Enzyme activity is sensitive to pH, and unsuitable pH can reduce metabolic reaction rates.",
  explanationSteps: [
    "Many metabolic pathways depend on enzymes operating within suitable pH ranges.",
    "Deviation from those ranges can reduce enzyme efficiency and metabolism.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "An organism survives a sudden environmental change, but its growth rate decreases. Which interpretation best distinguishes survival from successful growth?", styles: [] }],
    },
  ],
  question: "An organism survives a sudden environmental change, but its growth rate decreases. Which interpretation best distinguishes survival from successful growth?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Survival and growth",
  section: "objective",
  options: [
    { label: "A", value: "The organism can maintain essential functions but has fewer resources available for biomass production" },
    { label: "B", value: "Reduced growth proves that the organism is dead" },
    { label: "C", value: "Growth and survival are identical processes" },
    { label: "D", value: "Survival requires complete cessation of metabolism" },
  ],
  correctAnswers: ["The organism can maintain essential functions but has fewer resources available for biomass production"],
  explanation: "An organism may survive while allocating resources primarily to maintenance rather than growth.",
  explanationSteps: [
    "Essential metabolism can continue under stressful conditions.",
    "Limited resources may reduce the amount available for synthesis of new biomass.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A species produces many offspring, but only a small proportion survive to adulthood. Which factor would most directly explain why reproduction can still be advantageous to the species?", styles: [] }],
    },
  ],
  question: "A species produces many offspring, but only a small proportion survive to adulthood. Which factor would most directly explain why reproduction can still be advantageous to the species?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Reproduction and population continuity",
  section: "objective",
  options: [
    { label: "A", value: "Producing many offspring increases the probability that enough individuals survive to reproduce" },
    { label: "B", value: "High offspring mortality makes reproduction unnecessary" },
    { label: "C", value: "All offspring must survive for reproduction to have value" },
    { label: "D", value: "Reproduction only benefits individual organisms and never populations" },
  ],
  correctAnswers: ["Producing many offspring increases the probability that enough individuals survive to reproduce"],
  explanation: "High offspring mortality can be offset by producing numerous offspring, allowing some to reach reproductive age.",
  explanationSteps: [
    "Environmental hazards may eliminate many young individuals.",
    "Producing numerous offspring increases the chance that some survive and reproduce.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A researcher blocks a plant's ability to respond to gravity while leaving its growth processes intact. Which observation would most strongly confirm the successful disruption?", styles: [] }],
    },
  ],
  question: "A researcher blocks a plant's ability to respond to gravity while leaving its growth processes intact. Which observation would most strongly confirm the successful disruption?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Sensitivity and growth responses",
  section: "objective",
  options: [
    { label: "A", value: "The plant continues growing but no longer shows the normal directional growth associated with gravity" },
    { label: "B", value: "The plant immediately stops all respiration" },
    { label: "C", value: "The plant loses all ability to absorb water" },
    { label: "D", value: "The plant stops producing cells completely" },
  ],
  correctAnswers: ["The plant continues growing but no longer shows the normal directional growth associated with gravity"],
  explanation: "A response to gravity can be separated experimentally from the general process of growth.",
  explanationSteps: [
    "Growth can continue even if a specific stimulus-response pathway is disrupted.",
    "Loss of directional growth would indicate impaired sensitivity to gravity.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A researcher measures oxygen consumption in an organism before and during vigorous movement. Oxygen consumption increases substantially during movement. Which inference is best supported?", styles: [] }],
    },
  ],
  question: "A researcher measures oxygen consumption in an organism before and during vigorous movement. Oxygen consumption increases substantially during movement. Which inference is best supported?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Respiration and movement",
  section: "objective",
  options: [
    { label: "A", value: "The increased movement is associated with increased aerobic energy demand" },
    { label: "B", value: "Movement occurs without energy expenditure" },
    { label: "C", value: "Oxygen is used only for excretion" },
    { label: "D", value: "Movement prevents respiration from occurring" },
  ],
  correctAnswers: ["The increased movement is associated with increased aerobic energy demand"],
  explanation: "Greater aerobic activity requires increased oxygen availability for energy production.",
  explanationSteps: [
    "Vigorous movement increases ATP demand.",
    "Aerobic respiration responds by increasing oxygen utilization when available.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A population of organisms becomes isolated from the main population and experiences a different climate for many generations. Individuals with traits suited to the new climate become more common. Which process best explains the observation?", styles: [] }],
    },
  ],
  question: "A population of organisms becomes isolated from the main population and experiences a different climate for many generations. Individuals with traits suited to the new climate become more common. Which process best explains the observation?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Adaptation and environmental selection",
  section: "objective",
  options: [
    { label: "A", value: "Natural selection acting on inherited variation" },
    { label: "B", value: "Immediate transformation of every organism into the same form" },
    { label: "C", value: "Loss of all variation caused by reproduction" },
    { label: "D", value: "Random elimination of all traits regardless of their effects" },
  ],
  correctAnswers: ["Natural selection acting on inherited variation"],
  explanation: "Environmental conditions can favour individuals possessing inherited traits that improve survival or reproduction.",
  explanationSteps: [
    "The population contains inherited variation.",
    "The new climate favours some variants, increasing their representation over generations.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "An organism's body maintains a stable internal water concentration even though water intake varies greatly from day to day. Which conclusion is most appropriate?", styles: [] }],
    },
  ],
  question: "An organism's body maintains a stable internal water concentration even though water intake varies greatly from day to day. Which conclusion is most appropriate?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Water balance and homeostasis",
  section: "objective",
  options: [
    { label: "A", value: "The organism regulates water balance through coordinated physiological mechanisms" },
    { label: "B", value: "Water intake has no effect on living organisms" },
    { label: "C", value: "The organism cannot lose water through excretion" },
    { label: "D", value: "Stable internal water concentration occurs only in non-living systems" },
  ],
  correctAnswers: ["The organism regulates water balance through coordinated physiological mechanisms"],
  explanation: "Maintaining relatively stable internal water conditions despite variable intake indicates regulation.",
  explanationSteps: [
    "Water intake changes the amount of water entering the body.",
    "Regulatory processes adjust water loss and retention to maintain internal balance.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A researcher observes that an organism's rate of movement rises after feeding and falls when nutrients are depleted. Which explanation best connects the observations?", styles: [] }],
    },
  ],
  question: "A researcher observes that an organism's rate of movement rises after feeding and falls when nutrients are depleted. Which explanation best connects the observations?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Nutrition, energy and movement",
  section: "objective",
  options: [
    { label: "A", value: "Nutrient availability influences energy supply for movement" },
    { label: "B", value: "Movement does not require energy" },
    { label: "C", value: "Feeding directly replaces respiration" },
    { label: "D", value: "Nutrient depletion always increases metabolic activity indefinitely" },
  ],
  correctAnswers: ["Nutrient availability influences energy supply for movement"],
  explanation: "Movement requires energy, and nutrient availability influences the substrates available for energy production.",
  explanationSteps: [
    "Food provides substrates that can be metabolized.",
    "Reduced nutrient availability can limit energy production and consequently reduce activity.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A plant grows normally when supplied with water, mineral salts and light. When one mineral element is removed, growth becomes severely restricted although photosynthesis continues. Which conclusion is most reasonable?", styles: [] }],
    },
  ],
  question: "A plant grows normally when supplied with water, mineral salts and light. When one mineral element is removed, growth becomes severely restricted although photosynthesis continues. Which conclusion is most reasonable?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Growth and mineral requirements",
  section: "objective",
  options: [
    { label: "A", value: "Photosynthesis alone cannot supply every material required for normal growth" },
    { label: "B", value: "Mineral elements are unnecessary for plant growth" },
    { label: "C", value: "Water completely replaces mineral nutrients" },
    { label: "D", value: "Growth depends only on light intensity" },
  ],
  correctAnswers: ["Photosynthesis alone cannot supply every material required for normal growth"],
  explanation: "Plants require mineral elements for the synthesis and functioning of many cellular components.",
  explanationSteps: [
    "Photosynthesis supplies organic carbon compounds.",
    "Mineral nutrients are also required for normal synthesis, metabolism and development.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "An organism's rate of reproduction increases when environmental conditions improve, but its individual growth rate remains unchanged. Which conclusion is most appropriate?", styles: [] }],
    },
  ],
  question: "An organism's rate of reproduction increases when environmental conditions improve, but its individual growth rate remains unchanged. Which conclusion is most appropriate?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Reproduction and environmental conditions",
  section: "objective",
  options: [
    { label: "A", value: "Environmental conditions can influence different life processes to different degrees" },
    { label: "B", value: "All life processes must respond identically to environmental change" },
    { label: "C", value: "Growth and reproduction are always controlled by exactly the same factors" },
    { label: "D", value: "Improved conditions necessarily increase every physiological process equally" },
  ],
  correctAnswers: ["Environmental conditions can influence different life processes to different degrees"],
  explanation: "Different physiological processes have different limiting factors and regulatory mechanisms.",
  explanationSteps: [
    "The improved environment increases reproductive performance.",
    "The unchanged growth rate shows that the factors limiting growth may differ.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A scientist kills all cells in a tissue but leaves the tissue's original shape intact. Which observation would most clearly distinguish the dead tissue from living tissue?", styles: [] }],
    },
  ],
  question: "A scientist kills all cells in a tissue but leaves the tissue's original shape intact. Which observation would most clearly distinguish the dead tissue from living tissue?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Life and cellular activity",
  section: "objective",
  options: [
    { label: "A", value: "The dead tissue no longer performs metabolism or responds to stimuli" },
    { label: "B", value: "The dead tissue retains its original shape" },
    { label: "C", value: "The dead tissue contains previously formed structures" },
    { label: "D", value: "The dead tissue occupies physical space" },
  ],
  correctAnswers: ["The dead tissue no longer performs metabolism or responds to stimuli"],
  explanation: "Physical structure alone does not demonstrate life; active physiological processes do.",
  explanationSteps: [
    "Dead tissue may retain its form for some time.",
    "The absence of metabolism and responsiveness provides stronger evidence that it is no longer living.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A living organism is transferred from a moist environment to a dry environment. It develops a thicker outer covering and reduces the rate at which it loses water. Which interpretation best explains the change?", styles: [] }],
    },
  ],
  question: "A living organism is transferred from a moist environment to a dry environment. It develops a thicker outer covering and reduces the rate at which it loses water. Which interpretation best explains the change?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Adaptation to environmental conditions",
  section: "objective",
  options: [
    { label: "A", value: "The changes improve water conservation under the new environmental condition" },
    { label: "B", value: "The changes demonstrate that the organism no longer requires water" },
    { label: "C", value: "The changes prevent all metabolic reactions" },
    { label: "D", value: "The changes prove that water has no physiological role" },
  ],
  correctAnswers: ["The changes improve water conservation under the new environmental condition"],
  explanation: "Reducing water loss can improve survival in dry environments.",
  explanationSteps: [
    "Dry conditions increase the risk of dehydration.",
    "A thicker barrier and reduced water loss can help maintain internal water balance.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A researcher notices that an organism continues to respire after it has stopped feeding temporarily. Which explanation best accounts for this observation?", styles: [] }],
    },
  ],
  question: "A researcher notices that an organism continues to respire after it has stopped feeding temporarily. Which explanation best accounts for this observation?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Respiration and stored nutrients",
  section: "objective",
  options: [
    { label: "A", value: "The organism can utilize previously stored respiratory substrates" },
    { label: "B", value: "Respiration occurs without any substrate" },
    { label: "C", value: "Feeding is unnecessary for all living organisms permanently" },
    { label: "D", value: "Respiration is the same process as reproduction" },
  ],
  correctAnswers: ["The organism can utilize previously stored respiratory substrates"],
  explanation: "Organisms can store organic materials and use them later for energy production.",
  explanationSteps: [
    "Recent food intake is not the only source of respiratory substrates.",
    "Stored carbohydrates, fats or other organic compounds can continue supporting respiration temporarily.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A population is exposed to a new predator. Individuals with faster escape responses survive more frequently, and the trait is inherited. What would most likely happen after many generations?", styles: [] }],
    },
  ],
  question: "A population is exposed to a new predator. Individuals with faster escape responses survive more frequently, and the trait is inherited. What would most likely happen after many generations?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Sensitivity, survival and selection",
  section: "objective",
  options: [
    { label: "A", value: "The frequency of inherited traits associated with faster escape responses may increase" },
    { label: "B", value: "All individuals acquire faster responses immediately" },
    { label: "C", value: "Predation prevents inherited traits from being transmitted" },
    { label: "D", value: "The population becomes genetically identical in one generation" },
  ],
  correctAnswers: ["The frequency of inherited traits associated with faster escape responses may increase"],
  explanation: "Differential survival can increase the frequency of inherited advantageous traits over generations.",
  explanationSteps: [
    "Individuals with faster escape responses survive more often.",
    "If the trait is inherited, successful survivors are more likely to pass it to offspring.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A scientist observes that an organism increases its breathing rate immediately after strenuous activity and returns to its normal rate after several minutes. Which explanation best accounts for the recovery?", styles: [] }],
    },
  ],
  question: "A scientist observes that an organism increases its breathing rate immediately after strenuous activity and returns to its normal rate after several minutes. Which explanation best accounts for the recovery?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Regulation after activity",
  section: "objective",
  options: [
    { label: "A", value: "The organism's oxygen and carbon dioxide requirements return toward resting levels" },
    { label: "B", value: "Respiration permanently stops after exercise" },
    { label: "C", value: "Movement eliminates the need for oxygen" },
    { label: "D", value: "Breathing rate is unrelated to metabolic activity" },
  ],
  correctAnswers: ["The organism's oxygen and carbon dioxide requirements return toward resting levels"],
  explanation: "Breathing rate is linked to the metabolic demands of tissues and gas exchange requirements.",
  explanationSteps: [
    "Strenuous activity increases oxygen demand and carbon dioxide production.",
    "When activity declines, these demands decrease and breathing rate can return toward normal.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "An organism is able to survive a temporary shortage of food by reducing its activity and using stored energy reserves. Which combination of characteristics is demonstrated most clearly?", styles: [] }],
    },
  ],
  question: "An organism is able to survive a temporary shortage of food by reducing its activity and using stored energy reserves. Which combination of characteristics is demonstrated most clearly?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Survival, metabolism and regulation",
  section: "objective",
  options: [
    { label: "A", value: "Metabolic regulation, energy utilization and adaptation to environmental stress" },
    { label: "B", value: "Reproduction without energy expenditure" },
    { label: "C", value: "Growth without nutrient utilization" },
    { label: "D", value: "Excretion without metabolism" },
  ],
  correctAnswers: ["Metabolic regulation, energy utilization and adaptation to environmental stress"],
  explanation: "Reducing activity conserves energy while stored reserves provide substrates for continued metabolism.",
  explanationSteps: [
    "Food shortage reduces external energy supply.",
    "The organism adjusts activity and mobilizes stored energy to maintain essential functions.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},
{
  content: [
    {
      type: "text",
      order: 1,
      segments: [{ text: "A researcher finds that two organisms have similar structures but differ greatly in their ability to survive a particular environmental condition. Which factor would provide the strongest explanation?", styles: [] }],
    },
  ],
  question: "A researcher finds that two organisms have similar structures but differ greatly in their ability to survive a particular environmental condition. Which factor would provide the strongest explanation?",
  instruction: "Select the correct option.",
  topic: "A01 — Living Organisms — Physiological adaptation",
  section: "objective",
  options: [
    { label: "A", value: "Differences in physiological processes can influence survival even when external structures are similar" },
    { label: "B", value: "Similar structures guarantee identical physiological performance" },
    { label: "C", value: "Physiology has no relationship with survival" },
    { label: "D", value: "Environmental conditions affect structure but never internal processes" },
  ],
  correctAnswers: ["Differences in physiological processes can influence survival even when external structures are similar"],
  explanation: "Survival depends not only on anatomy but also on physiological tolerance and regulation.",
  explanationSteps: [
    "Similar structures do not necessarily imply identical internal processes.",
    "Differences in physiological responses can determine tolerance to environmental conditions.",
  ],
  difficulty: "hard",
  examType: "jamb",
  apiSubjectName: "Biology",
  isMultipleAnswer: false,
},



];

export default jambBiologyHardQuestions;
